name: canta_cuvantul
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  gradient_widgets: ^0.5.1
  sqflite: ^1.3.0
  path_provider: any  
  shared_preferences: ^0.5.7+1
  assets_audio_player: ^1.6.2+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/
  fonts:
    - family: Vibur
      fonts:
        - asset: fonts/Vibur-Regular.ttf
    
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans.ttf
    
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf



  